sudo: required
dist: trusty

cache:
  directories:
    - node_modules
    - client/node_modules
    - client/apps/hello_world/node_modules

branches:
  only:
  - master
  - staging
  - stable

before_install:
  - cp .env.example .env
  - nvm install 8.1.0
  - nvm use 8.1.0
  - npm install -g yarn

install:
  - yarn

before_script:
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script:
  - yarn test
