language: ruby
sudo: required
dist: trusty

env:
  - CXX=g++-4.8

addons:
  postgresql: "9.5"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

cache:
  bundler: true
  directories:
    - node_modules
    - client/node_modules
    - client/apps/hello_world/node_modules

branches:
  only:
  - master
  - staging
  - stable

services:
  - postgresql

before_install:
  - cp config/secrets.example.yml config/secrets.yml
  - cp config/ci.database.yml config/database.yml
  - cp .env.example .env
  - cp client/ci.karma.conf.js client/karma.conf.js
  - nvm install 7.5.0
  - nvm use 7.5.0
  - npm install -g yarn

install:
  - bundle install --path vendor/bundle
  - yarn

before_script:
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - bundle exec rake db:create
  - bundle exec rake db:schema:load

script:
  - ./bin/ci
  - yarn test
  - yarn coverage
