# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
Defaults: &defaults

  admin_name: Administrator
  admin_email: admin@example.com
  admin_password: changeme

  encryption_key: '<Run rake secret to get a value to put here>'

  # Main application settings
  application_code: <%= ENV["APP_SUBDOMAIN"] || "reactrailsstarterapp" %>
  application_name: "React Starter App"
  application_url: <%= %Q{#{ENV["APP_SUBDOMAIN"]}.#{ENV["APP_URL"] || "lvh.me"}} %>

  # Email Settings
  domain_name: <%= ENV["APP_URL"] || "reactrailsstarterapp.com" %>
  email_provider_username: admin@example.com
  email_provider_password: changeme

  # Assets (webpack server in dev mode)
  assets_url: <%= ENV["ASSETS_URL"] || "http://localhost:8080" %>

  auth0_client_id: react_rails_starter_app
  auth0_client_secret: '<Run rake secret to get a value to put here>'

development:
  <<: *defaults

  secret_key_base: '<Run rake secret to get a value to put here>'

test:
  <<: *defaults

  secret_key_base: '<Run rake secret to get a value to put here>'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *defaults

  application_url: <%= "#{ENV['APP_SUBDOMAIN']}.herokuapp.com" %>

  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  encryption_key: '<Run rake secret to get a value to put here>'
le/settings
  # Push the "New Access Token" button
  canvas_token: <%= ENV["CANVAS_TOKEN"] %>

development:
  <<: *defaults

  secret_key_base: '<Run rake secret to get a value to put here>'

test:
  <<: *defaults

  secret_key_base: '<Run rake secret to get a value to put here>'

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *defaults

  application_url: <%= "#{ENV['APP_SUBDOMAIN']}.herokuapp.com" %>

  lti_launch_domain: ltistarterapp.com

  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  canvas_url: 'https://canvas.instructure.com'

  encryption_key: '<Run rake secret to get a value to put here>'
